---

- hosts: i5gmc_nginx
  tasks:
  - name: Query IP of host
    shell: "echo {{ansible_env.SSH_CONNECTION}}|awk '{print $3}'"
    register: _local_ip
  
  - name: Set vars
    set_fact:
      module=i5gmc_nginx
      tag=1.19.7.1
      localip={{_local_ip.stdout}}
    ignore_errors: yes
  
- hosts: i5gmc_nginx
  become: true
  become_method: sudo
  become_user: 'root'
  roles: 
    - i5gmc_nginx
    
